-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 14:12:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DreamJobBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DreamJobBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DreamJobBD` DEFAULT CHARACTER SET utf8 ;
USE `DreamJobBD` ;

-- -----------------------------------------------------
-- Table `DreamJobBD`.`chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamJobBD`.`chef` (
  `numcinchef` VARCHAR(8) NOT NULL,
  `nomchef` VARCHAR(30) NOT NULL,
  `prenomchef` VARCHAR(30) NOT NULL,
  `numtelchef` VARCHAR(8) NULL,
  `sexechef` VARCHAR(30) NOT NULL,
  `datedenaissancechef` DATE NOT NULL,
  `emailchef` VARCHAR(30) NOT NULL,
  `motdepassechef` VARCHAR(30) NOT NULL,
  `nomdubusiness` VARCHAR(30) NOT NULL,
  `numteldetravail` VARCHAR(8) NOT NULL,
  `domainedetravail` VARCHAR(30) NOT NULL,
  `adresse` VARCHAR(30) NULL,
  PRIMARY KEY (`numcinchef`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamJobBD`.`chomeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamJobBD`.`chomeur` (
  `numcinchomeur` VARCHAR(8) NOT NULL,
  `nomchomeur` VARCHAR(30) NULL,
  `prenomchomeur` VARCHAR(30) NULL,
  `numtelchomeur` VARCHAR(8) NULL,
  `sexechomeur` VARCHAR(30) NULL,
  `datedenaissancechomeur` DATE NULL,
  `emailchomeur` VARCHAR(30) NULL,
  `motdepassechomeur` VARCHAR(30) NULL,
  `niveaud'education` VARCHAR(30) NULL,
  `specialite` VARCHAR(30) NULL,
  `langue` VARCHAR(45) NULL,
  `ajouter` LONGTEXT NULL,
  PRIMARY KEY (`numcinchomeur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamJobBD`.`chercher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamJobBD`.`chercher` (
  `chef_numcinchef` VARCHAR(8) NOT NULL,
  `chomeur_numcinchomeur` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`chef_numcinchef`, `chomeur_numcinchomeur`),
  CONSTRAINT `fk_chef_has_chomeur_chef`
    FOREIGN KEY (`chef_numcinchef`)
    REFERENCES `DreamJobBD`.`chef` (`numcinchef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chef_has_chomeur_chomeur1`
    FOREIGN KEY (`chomeur_numcinchomeur`)
    REFERENCES `DreamJobBD`.`chomeur` (`numcinchomeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_chef_has_chomeur_chomeur1_idx` ON `DreamJobBD`.`chercher` (`chomeur_numcinchomeur` ASC) VISIBLE;

CREATE INDEX `fk_chef_has_chomeur_chef_idx` ON `DreamJobBD`.`chercher` (`chef_numcinchef` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
